global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "flask-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]   # עדכן אם שם השירות/הפורט שונים

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "node"
    static_configs:
      - targets: ["127.0.0.1:9100"] # node-exporter במצב host
